#!/bin/bash

set -e # abort script at first error

##### REFERENCE START - https://stackoverflow.com/a/10015707 ####
# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty
##### REFERENCE END - https://stackoverflow.com/a/10015707 ####

##### REFERENCE START - https://stackoverflow.com/a/20983251
# Set variable to use to display colour
# tput - https://linux.die.net/man/1/tput
RED=`tput setaf 1`
GREEN=`tput setaf 2`
YELLOW=`tput setaf 3`
BLUE=`tput setaf 4`
MAGENTA=`tput setaf 5`
CYAN=`tput setaf 6`
WHITE=`tput setaf 7`
RESET=`tput sgr0`
##### REFERENCE END - https://stackoverflow.com/a/20983251

echo "COMMIT-MSG"

COMMIT_MSG_FILE=$1

MSG=$(< $1)

# check that the file is 5 lines long
INVALID_MSG=""
LINE_COUNT=`wc -l < "$COMMIT_MSG_FILE"`
if [[ $LINE_COUNT != 5 ]]; then
  INVALID_MSG="Commit message not 5 lines"
else
  LINES=("$(sed -n '1p' < "$COMMIT_MSG_FILE")" # Array containing first 5 lines of commit msg
  "$(sed -n '2p' < "$COMMIT_MSG_FILE")"
  "$(sed -n '3p' < "$COMMIT_MSG_FILE")"
  "$(sed -n '4p' < "$COMMIT_MSG_FILE")"
  "$(sed -n '5p' < "$COMMIT_MSG_FILE")")
  echo ${LINES[0]}
  echo ${LINES[1]}
  echo ${LINES[2]}
  echo ${LINES[4]}
  if [ -z "${LINES[0]}"] || [ -z "${LINES[2]}" ] || [ -z "${LINES[4]}" ]; then # Lines 1,3,5 should contain text (not be blank)
    INVALID_MSG="Lines 1,3,5 should contain text (not be blank)"
  elif [ -n "${LINES[1]}" ] || [ -n "${LINES[3]}" ]; then # Lines 2 and 4 should be blank
    INVALID_MSG="Lines 2 and 4 should be blank"
  fi
fi

# Inform user if commit message if not formatted correctly
if [[ $INVALID_MSG ]]; then
  echo "${RED}Commit message not formatted correctly${RESET}"
  echo "${RED}${INVALID_MSG}${RESET}"
  # Display format expected
  echo "Should be formatted as follows:"
  echo "<SUMMARY - 1 line>"
  echo ""
  echo "<WHY - 1 line>" 
  echo ""
  echo "<WHAT - 1 line>"
  echo "${YELLOW}Your commit message:${RESET}"
  # Display the commit message
  echo "$(cat "$COMMIT_MSG_FILE")"
  read -n 1 -p "Continue with commit? (y/n) " KEY
  if [[ "$KEY" != "y" ]]; then
    # Abort commit
    echo ""
    echo "Commit aborted"
    exit 1
  fi
fi

echo "${GREEN}Commited with message:${RESET}"
echo "${MSG}"
