#!/bin/bash

##### REFERENCE START - https://stackoverflow.com/a/10015707 ####
# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty
##### REFERENCE END - https://stackoverflow.com/a/10015707 ####

##### START - Sample git hook provided ###############################
set -e # using the options command to abort script at first error
echo
echo "PRE-COMMIT"

EMAIL=$(git config user.email)

# make sure the user has registered a valid university email address
if [[ $EMAIL != *"@coventry.ac.uk" ]]; then
	echo "  invalid config settings"
	echo "  Your registered email is currently '$EMAIL'"
	echo "  please run the following git commands:"
	echo "    $ git config user.email xxx@coventry.ac.uk"
	echo "    $ git config user.name 'zzz'"
	echo "  where 'xxx' is your university username"
	echo "  and 'zzz' is your name as it appears on your university ID badge"
	echo
	exit 1
fi

# see if the user is trying to merge a branch into master
branch="$(git rev-parse --abbrev-ref HEAD)"
if [[ $2 == 'merge' ]]; then
	echo "merging branch"
	if [[ "$branch" == "master" ]]; then
		echo "  trying to merge into the 'master' branch"
		echo "  you should push the local branch to GitHub"
		echo "  and merge to master using a pull request"
		echo
		exit 1
	fi
fi

# see if the user is trying to commit to the master branch
if [ "$branch" = "master" ]; then
	read -p "  You are about to commit to the master branch, are you sure? [y|n] " -n 1 -r < /dev/tty
	echo
	if echo $REPLY | grep -E '^[Yy]$' > /dev/null
	then
		exit 0 # commit will execute
	fi
	exit 1 # commit will not execute
fi
##### END - Sample git hook provided ###############################

# Abort commit if a test fails
numberOfFailedTests=$(node_modules/.bin/ava --tap | grep fail | awk '{print $3}')
if [[ $numberOfFailedTests != 0  ]]; then
	echo 'FAIL - Not all tests were passed'
	echo 'Commit aborted'
	exit 1
fi

# Abort commit if linter has problem
problemFound=$(node_modules/.bin/eslint . | grep problem | wc -l)
if [ $problemFound = 1  ]; then
	echo 'FAIL - Linter problem(s) found'
  read -p "Run linter with --fix tag? (y/n) " RE_RUN_LINTER
  if [[ "$RE_RUN_LINTER" == "y" ]]; then
    problemFound=$(node_modules/.bin/eslint . --fix | grep problem | wc -l)
    if [ $problemFound = 1  ]; then
      echo 'FAIL - Linter problem(s) found after running with --fix'
      echo 'Run linter to see details.'
      exit 1
    fi
  else
    echo 'Commit aborted'
    exit 1
  fi
fi

# Run the jsDocs
node_modules/.bin/jsdoc -c jsdoc.conf
